"""
Fetch the guest animals' pictures from Twemoji and write them into the server.

YARG cannot draw colour emoji from text: TextMeshPro reads glyph outlines, and no font
YARG has carries emoji. So when YASS shows the next player under its QR code in YARG
(through the Setlist Bridge plugin), it sends a picture of the guest's animal along. The
pictures are Twemoji's, one PNG per animal at 72x72, embedded in the server as base64 so
they ship inside the bundle and nothing is fetched at party time.

This script is how they got there, and how to get them again after an animal is added to
GUEST_ANIMALS in shared/src/types.ts. It reads the animals from that file, downloads each
from a pinned Twemoji release, checks it is a PNG, and writes
server/src/core/guestEmoji.ts. Standard library only.

    python server/scripts/fetch-guest-emoji.py

Twemoji's graphics are CC-BY 4.0: https://github.com/jdecked/twemoji — credited in
THIRD-PARTY-NOTICES.md. Bump TWEMOJI_VERSION deliberately and look at the result.
"""

import base64
import pathlib
import re
import sys
import urllib.request

TWEMOJI_VERSION = "v17.0.3"
URL = "https://raw.githubusercontent.com/jdecked/twemoji/{version}/assets/72x72/{code}.png"

ROOT = pathlib.Path(__file__).resolve().parents[2]
TYPES = ROOT / "shared" / "src" / "types.ts"
OUTPUT = ROOT / "server" / "src" / "core" / "guestEmoji.ts"

PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def animals():
    """The emoji in GUEST_ANIMALS, in order."""
    text = TYPES.read_text(encoding="utf-8")
    block = re.search(r"export const GUEST_ANIMALS = \[(.*?)\] as const", text, re.S)
    if block is None:
        sys.exit(f"GUEST_ANIMALS not found in {TYPES}")
    found = re.findall(r"emoji: '([^']+)'", block.group(1))
    if not found:
        sys.exit("GUEST_ANIMALS has no emoji in it")
    return found


def twemoji_code(emoji):
    """Twemoji's file name: code points in lowercase hex, joined by '-', without FE0F."""
    return "-".join(f"{ord(c):x}" for c in emoji if ord(c) != 0xFE0F)


def fetch(code):
    url = URL.format(version=TWEMOJI_VERSION, code=code)
    with urllib.request.urlopen(url, timeout=30) as response:
        data = response.read()
    if not data.startswith(PNG_SIGNATURE):
        sys.exit(f"{url} is not a PNG")
    return data


def main():
    lines = []
    total = 0
    for emoji in animals():
        code = twemoji_code(emoji)
        data = fetch(code)
        total += len(data)
        lines.append(f"  '{emoji}': '{base64.b64encode(data).decode('ascii')}',")
        print(f"{emoji} {code}.png {len(data)} bytes")

    OUTPUT.write_text(
        "/**\n"
        " * The guest animals as pictures, for YARG — which cannot draw colour emoji from text.\n"
        " *\n"
        f" * Twemoji {TWEMOJI_VERSION} (https://github.com/jdecked/twemoji), 72x72 PNG, base64,\n"
        " * CC-BY 4.0. Generated by server/scripts/fetch-guest-emoji.py; run that rather than\n"
        " * editing this, after changing GUEST_ANIMALS in shared/src/types.ts.\n"
        " */\n"
        "\n"
        "export const GUEST_EMOJI_PNG: Readonly<Record<string, string>> = {\n"
        + "\n".join(lines)
        + "\n}\n",
        encoding="utf-8",
        newline="\n",
    )
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(lines)} pictures, {total} bytes of PNG")


if __name__ == "__main__":
    main()
